<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Barang;
use App\Models\Kategori;

class BarangSeeder extends Seeder
{
    public function run()
    {
        // Ambil semua kategori
        $kategoris = Kategori::pluck('id', 'nama');

        $barangs = [
            // Peralatan Ibadah (Kategori ID: 1)
            [
                'kode_barang' => 'PIB001',
                'nama' => 'Alkitab',
                'deskripsi' => 'Alkitab untuk keperluan ibadah',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB002',
                'nama' => 'Buku Kidung Jemaat',
                'deskripsi' => 'Buku nyanyian untuk jemaat',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 100,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB003',
                'nama' => 'Patena',
                'deskripsi' => 'Wadah roti suci untuk perjamuan kudus',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB004',
                'nama' => 'Piala Perjamuan',
                'deskripsi' => 'Piala untuk anggur perjamuan kudus',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 350000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB005',
                'nama' => 'Hosti',
                'deskripsi' => 'Roti suci untuk perjamuan kudus',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'box',
                'stok' => 20,
                'harga' => 50000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB006',
                'nama' => 'Anggur Perjamuan',
                'deskripsi' => 'Anggur untuk perjamuan kudus',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'botol',
                'stok' => 15,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB007',
                'nama' => 'Lilin Paskah',
                'deskripsi' => 'Lilin untuk ibadah Paskah',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 100,
                'harga' => 5000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB008',
                'nama' => 'Palang',
                'deskripsi' => 'Palang kayu untuk prosesi',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB009',
                'nama' => 'Tempat Air Suci',
                'deskripsi' => 'Wadah air suci untuk pembasuhan',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 180000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PIB010',
                'nama' => 'Spons Pembasuh',
                'deskripsi' => 'Spons untuk pembasuhan kaki',
                'kategori_id' => $kategoris['Peralatan Ibadah'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 25000,
                'status' => 'aktif',
            ],

            // Peralatan Elektronik (Kategori ID: 2)
            [
                'kode_barang' => 'ELK001',
                'nama' => 'Mikrophone Wireless',
                'deskripsi' => 'Mikrophone untuk khotbah dan pujian',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 5,
                'harga' => 1500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK002',
                'nama' => 'Sound System Mixer',
                'deskripsi' => 'Mixer audio untuk sound system',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 8500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK003',
                'nama' => 'Speaker Aktif',
                'deskripsi' => 'Speaker aktif untuk sound system gereja',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 4,
                'harga' => 3500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK004',
                'nama' => 'Proyektor LCD',
                'deskripsi' => 'Proyektor untuk presentasi dan ibadah',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 2,
                'harga' => 7500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK005',
                'nama' => 'Layar Proyeksi',
                'deskripsi' => 'Layar untuk proyektor',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 2500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK006',
                'nama' => 'Kamera Video',
                'deskripsi' => 'Kamera untuk rekaman ibadah',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 2,
                'harga' => 12500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK007',
                'nama' => 'Tripod Kamera',
                'deskripsi' => 'Tripod untuk penyangga kamera',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 750000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK008',
                'nama' => 'Laptop Presentasi',
                'deskripsi' => 'Laptop untuk presentasi dan ibadah',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 15000000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK009',
                'nama' => 'Gitar Akustik',
                'deskripsi' => 'Gitar untuk pujian',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 2500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ELK010',
                'nama' => 'Keyboard Elektrik',
                'deskripsi' => 'Keyboard untuk pujian',
                'kategori_id' => $kategoris['Peralatan Elektronik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 8500000,
                'status' => 'aktif',
            ],

            // Furniture (Kategori ID: 3)
            [
                'kode_barang' => 'FRN001',
                'nama' => 'Kursi Jemaat',
                'deskripsi' => 'Kursi untuk jemaat beribadah',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 200,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN002',
                'nama' => 'Kursi Pastor',
                'deskripsi' => 'Kursi khusus untuk pendeta',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 750000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN003',
                'nama' => 'Meja Altar',
                'deskripsi' => 'Meja untuk altar',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 1,
                'harga' => 1500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN004',
                'nama' => 'Mimbar',
                'deskripsi' => 'Mimbar untuk khotbah',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 1,
                'harga' => 2500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN005',
                'nama' => 'Meja Lipat',
                'deskripsi' => 'Meja lipat untuk acara gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN006',
                'nama' => 'Kursi Lipat',
                'deskripsi' => 'Kursi lipat untuk acara gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 100,
                'harga' => 85000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN007',
                'nama' => 'Lemari Arsip',
                'deskripsi' => 'Lemari untuk menyimpan dokumen gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 1500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN008',
                'nama' => 'Rak Buku',
                'deskripsi' => 'Rak buku untuk perpustakaan gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 750000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN009',
                'nama' => 'Bufet',
                'deskripsi' => 'Bufet untuk ruang tamu gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 3500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'FRN010',
                'nama' => 'Tempat Sampah',
                'deskripsi' => 'Tempat sampah untuk gereja',
                'kategori_id' => $kategoris['Furniture'],
                'satuan' => 'buah',
                'stok' => 15,
                'harga' => 150000,
                'status' => 'aktif',
            ],

            // Peralatan Dapur (Kategori ID: 4)
            [
                'kode_barang' => 'DPR001',
                'nama' => 'Kompor Gas',
                'deskripsi' => 'Kompor gas untuk dapur gereja',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'unit',
                'stok' => 2,
                'harga' => 750000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR002',
                'nama' => 'Tabung Gas',
                'deskripsi' => 'Tabung gas 3kg untuk dapur',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR003',
                'nama' => 'Kulkas',
                'deskripsi' => 'Kulkas untuk menyimpan makanan',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 5500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR004',
                'nama' => 'Panci Set',
                'deskripsi' => 'Set panci untuk memasak',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'set',
                'stok' => 3,
                'harga' => 350000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR005',
                'nama' => 'Piring Melamin',
                'deskripsi' => 'Piring untuk acara makan bersama',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'buah',
                'stok' => 200,
                'harga' => 15000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR006',
                'nama' => 'Sendok Garpu',
                'deskripsi' => 'Sendok garpu set untuk makan',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'set',
                'stok' => 200,
                'harga' => 10000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR007',
                'nama' => 'Gelas Plastik',
                'deskripsi' => 'Gelas untuk minuman acara gereja',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'buah',
                'stok' => 300,
                'harga' => 5000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR008',
                'nama' => 'Dispenser',
                'deskripsi' => 'Dispenser air minum',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'unit',
                'stok' => 2,
                'harga' => 350000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR009',
                'nama' => 'Galon Air',
                'deskripsi' => 'Galon air untuk dispenser',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DPR010',
                'nama' => 'Rice Cooker',
                'deskripsi' => 'Penanak nasi untuk dapur gereja',
                'kategori_id' => $kategoris['Peralatan Dapur'],
                'satuan' => 'unit',
                'stok' => 2,
                'harga' => 450000,
                'status' => 'aktif',
            ],

            // Peralatan Kebersihan (Kategori ID: 5)
            [
                'kode_barang' => 'KLB001',
                'nama' => 'Sapu Lidi',
                'deskripsi' => 'Sapu untuk membersihkan halaman',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB002',
                'nama' => 'Sapu Ijuk',
                'deskripsi' => 'Sapu untuk membersihkan lantai',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 8,
                'harga' => 35000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB003',
                'nama' => 'Pel Lantai',
                'deskripsi' => 'Pel untuk membersihkan lantai',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 45000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB004',
                'nama' => 'Kain Lap',
                'deskripsi' => 'Kain lap untuk membersihkan',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 30,
                'harga' => 10000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB005',
                'nama' => 'Deterjen',
                'deskripsi' => 'Deterjen untuk mencuci',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'kg',
                'stok' => 20,
                'harga' => 12000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB006',
                'nama' => 'Spons Cuci Piring',
                'deskripsi' => 'Spons untuk cuci piring',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 20,
                'harga' => 5000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB007',
                'nama' => 'Sabun Cuci Tangan',
                'deskripsi' => 'Sabun cuci tangan cair',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'botol',
                'stok' => 15,
                'harga' => 15000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB008',
                'nama' => 'Tisu Gulung',
                'deskripsi' => 'Tisu gulung untuk toilet',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 25,
                'harga' => 10000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB009',
                'nama' => 'Tempat Sampah Besar',
                'deskripsi' => 'Tempat sampah besar outdoor',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'KLB010',
                'nama' => 'Sikat WC',
                'deskripsi' => 'Sikat untuk membersihkan toilet',
                'kategori_id' => $kategoris['Peralatan Kebersihan'],
                'satuan' => 'buah',
                'stok' => 8,
                'harga' => 15000,
                'status' => 'aktif',
            ],

            // Alat Tulis Kantor (Kategori ID: 6)
            [
                'kode_barang' => 'ATK001',
                'nama' => 'Kertas A4',
                'deskripsi' => 'Kertas untuk keperluan administrasi',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'rim',
                'stok' => 25,
                'harga' => 45000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK002',
                'nama' => 'Pulpen',
                'deskripsi' => 'Pulpen untuk menulis',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 3000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK003',
                'nama' => 'Pensil',
                'deskripsi' => 'Pensil untuk menulis',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 30,
                'harga' => 2000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK004',
                'nama' => 'Penggaris',
                'deskripsi' => 'Penggaris 30cm',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 20,
                'harga' => 5000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK005',
                'nama' => 'Spidol',
                'deskripsi' => 'Spidol whiteboard',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 15,
                'harga' => 10000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK006',
                'nama' => 'Tinta Printer',
                'deskripsi' => 'Tinta untuk printer kantor',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 4,
                'harga' => 125000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK007',
                'nama' => 'Kertas HVS',
                'deskripsi' => 'Kertas HVS 80gr',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'rim',
                'stok' => 10,
                'harga' => 50000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK008',
                'nama' => 'Map Plastik',
                'deskripsi' => 'Map plastik untuk dokumen',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 5000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK009',
                'nama' => 'Stapler',
                'deskripsi' => 'Stapler untuk kertas',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'ATK010',
                'nama' => 'Isi Staples',
                'deskripsi' => 'Isi staples untuk stapler',
                'kategori_id' => $kategoris['Alat Tulis Kantor'],
                'satuan' => 'pack',
                'stok' => 10,
                'harga' => 7500,
                'status' => 'aktif',
            ],

            // Dekorasi & Perlengkapan (Kategori ID: 7)
            [
                'kode_barang' => 'DKR001',
                'nama' => 'Bunga Plastik',
                'deskripsi' => 'Bunga hias untuk dekorasi altar',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 15,
                'harga' => 35000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR002',
                'nama' => 'Kain Altar',
                'deskripsi' => 'Kain untuk menutupi meja altar',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR003',
                'nama' => 'Tiang Bunga',
                'deskripsi' => 'Tiang bunga untuk dekorasi',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 6,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR004',
                'nama' => 'Lilin Gereja',
                'deskripsi' => 'Lilin untuk penerangan gereja',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 7500,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR005',
                'nama' => 'Tirai Gereja',
                'deskripsi' => 'Tirai untuk jendela gereja',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'pasang',
                'stok' => 10,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR006',
                'nama' => 'Karpet Merah',
                'deskripsi' => 'Karpet untuk jalur altar',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'meter',
                'stok' => 20,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR007',
                'nama' => 'Tempat Lilin',
                'deskripsi' => 'Tempat lilin untuk altar',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 50000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR008',
                'nama' => 'Salib Dinding',
                'deskripsi' => 'Salib untuk dinding gereja',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR009',
                'nama' => 'Lampu Hias',
                'deskripsi' => 'Lampu hias untuk gereja',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 8,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'DKR010',
                'nama' => 'Tanaman Hias',
                'deskripsi' => 'Tanaman hias untuk gereja',
                'kategori_id' => $kategoris['Dekorasi & Perlengkapan'],
                'satuan' => 'buah',
                'stok' => 12,
                'harga' => 50000,
                'status' => 'aktif',
            ],

            // Pakaian & Seragam (Kategori ID: 8)
            [
                'kode_barang' => 'PSJ001',
                'nama' => 'Jubah Pastor',
                'deskripsi' => 'Jubah untuk pendeta',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 750000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ002',
                'nama' => 'Stola',
                'deskripsi' => 'Stola untuk pendeta',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ003',
                'nama' => 'Seragam Paduan Suara',
                'deskripsi' => 'Seragam untuk paduan suara',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'set',
                'stok' => 20,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ004',
                'nama' => 'Seragam Pelayan',
                'deskripsi' => 'Seragam untuk pelayan gereja',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'set',
                'stok' => 15,
                'harga' => 125000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ005',
                'nama' => 'Tali Dasi',
                'deskripsi' => 'Tali dasi untuk pelayan',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 20,
                'harga' => 35000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ006',
                'nama' => 'Dasi Kupu-kupu',
                'deskripsi' => 'Dasi kupu-kupu untuk pelayan',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 15,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ007',
                'nama' => 'Nama Tag',
                'deskripsi' => 'Nama tag untuk pelayan',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 50,
                'harga' => 15000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ008',
                'nama' => 'Topi Pelayan',
                'deskripsi' => 'Topi untuk pelayan gereja',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 15,
                'harga' => 35000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ009',
                'nama' => 'Syal Paduan Suara',
                'deskripsi' => 'Syal untuk paduan suara',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'buah',
                'stok' => 20,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'PSJ010',
                'nama' => 'Sarung Tangan',
                'deskripsi' => 'Sarung tangan putih untuk pelayan',
                'kategori_id' => $kategoris['Pakaian & Seragam'],
                'satuan' => 'pasang',
                'stok' => 15,
                'harga' => 20000,
                'status' => 'aktif',
            ],

            // Alat Musik (Kategori ID: 9)
            [
                'kode_barang' => 'MUS001',
                'nama' => 'Organ Gereja',
                'deskripsi' => 'Organ untuk ibadah',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 25000000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS002',
                'nama' => 'Piano',
                'deskripsi' => 'Piano untuk ibadah',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 50000000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS003',
                'nama' => 'Drum Set',
                'deskripsi' => 'Drum set untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'set',
                'stok' => 1,
                'harga' => 15000000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS004',
                'nama' => 'Bass Elektrik',
                'deskripsi' => 'Bass elektrik untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'unit',
                'stok' => 1,
                'harga' => 8500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS005',
                'nama' => 'Gitar Akustik',
                'deskripsi' => 'Gitar akustik untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 2500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS006',
                'nama' => 'Gitar Elektrik',
                'deskripsi' => 'Gitar elektrik untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 1,
                'harga' => 4500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS007',
                'nama' => 'Biola',
                'deskripsi' => 'Biola untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 7500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS008',
                'nama' => 'Saksofon',
                'deskripsi' => 'Saksofon untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 1,
                'harga' => 12500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS009',
                'nama' => 'Terompet',
                'deskripsi' => 'Terompet untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 3500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MUS010',
                'nama' => 'Tamborin',
                'deskripsi' => 'Tamborin untuk pujian',
                'kategori_id' => $kategoris['Alat Musik'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 150000,
                'status' => 'aktif',
            ],

            // Perlengkapan Maintenance (Kategori ID: 10)
            [
                'kode_barang' => 'MTN001',
                'nama' => 'Tangga Lipat',
                'deskripsi' => 'Tangga lipat untuk perawatan',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 350000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN002',
                'nama' => 'Tool Set',
                'deskripsi' => 'Set peralatan tukang',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'set',
                'stok' => 1,
                'harga' => 1500000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN003',
                'nama' => 'Cat Tembok',
                'deskripsi' => 'Cat untuk perawatan gedung',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'kaleng',
                'stok' => 5,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN004',
                'nama' => 'Kuas Cat',
                'deskripsi' => 'Kuas untuk mengecat',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 10,
                'harga' => 25000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN005',
                'nama' => 'Sekop',
                'deskripsi' => 'Sekop untuk kebun gereja',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 75000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN006',
                'nama' => 'Cangkul',
                'deskripsi' => 'Cangkul untuk kebun gereja',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 3,
                'harga' => 50000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN007',
                'nama' => 'Selang Air',
                'deskripsi' => 'Selang air untuk kebun',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'meter',
                'stok' => 50,
                'harga' => 15000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN008',
                'nama' => 'Sprayer',
                'deskripsi' => 'Sprayer untuk menyemprot',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 2,
                'harga' => 150000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN009',
                'nama' => 'Obeng Set',
                'deskripsi' => 'Set obeng untuk perbaikan',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'set',
                'stok' => 1,
                'harga' => 250000,
                'status' => 'aktif',
            ],
            [
                'kode_barang' => 'MTN010',
                'nama' => 'Lampu Darurat',
                'deskripsi' => 'Lampu darurat untuk listrik padam',
                'kategori_id' => $kategoris['Perlengkapan Maintenance'],
                'satuan' => 'buah',
                'stok' => 5,
                'harga' => 35000,
                'status' => 'aktif',
            ],
        ];

        foreach ($barangs as $barang) {
            Barang::create($barang);
        }
    }
}
